spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerceDb
    username: postgres     # Add your actual database username
    password: 971997abcdef.     # Add your actual database password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop     # Set it to `update` or `validate` for production
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
